### ISSUE TITLE
Use of plugin with AVR-GCC 9.2.0 on windows

### ISSUE THREAD

**Issue by theAndreas** [jcmvbkbc/avr-flash-vtbl#1]
Hello,

built the plugin on linux with g++-8 for the avr-g++ 9.2.0 from this side:
https://blog.zakkemble.net/avr-gcc-builds/

Tried the plugin on windows with the following command:
D:\avr-gcc-9.2.0-x64-mingw\bin\avr-g++.exe" -o Wordclock.elf  Sketch.o ...  -Wl,-Map="Wordclock.map" -Wl,--start-group -Wl,-lm -Wl,-lArduinoCore  -Wl,--end-group -Wl,-L"../../.." -Wl,-L"C:\Users\aburn\Documents\GitHub\Wordclock\Wordclock_xmegaForArduino\Wordclock\ArduinoCore\Debug"  -Wl,--gc-sections  -mmcu=atxmega32e5  -Os -fplugin=avr-flash-vtbl.so  

Got no error and the elf file was created. But in the map file it seems the vtables are still in the .rodata section.

```
 .rodata._ZTV14HardwareSerial
                0x0000000000802014       0x10 C:\Users\aburn\Documents\GitHub\Wordclock\Wordclock_xmegaForArduino\Wordclock\ArduinoCore\Debug\libArduinoCore.a(HardwareSerial.o)
                0x0000000000802014                _ZTV14HardwareSerial
 .rodata._ZTV7TwoWire
                0x0000000000802024       0x10 C:\Users\aburn\Documents\GitHub\Wordclock\Wordclock_xmegaForArduino\Wordclock\ArduinoCore\Debug\libArduinoCore.a(XWire.o)
                0x0000000000802024                _ZTV7TwoWire
```

Is this correct? Is there anything still to do? Is the plugin not compatible to the used compiler?

Thanks in advance!

Best regards Andreas

**Comment by jcmvbkbc** [comment]
> Tried the plugin on windows with the following command:
> D:\avr-gcc-9.2.0-x64-mingw\bin\avr-g++.exe" -o Wordclock.elf Sketch.o ... -Wl,-Map="Wordclock.map" -Wl,--start-group -Wl,-lm -Wl,-lArduinoCore -Wl,--end-group -Wl,-L"../../.." -Wl,-L"C:\Users\aburn\Documents\GitHub\Wordclock\Wordclock_xmegaForArduino\Wordclock\ArduinoCore\Debug" -Wl,--gc-sections -mmcu=atxmega32e5 -Os -fplugin=avr-flash-vtbl.so

This command only does application linking from object files and libraries. The plugin is for the compiling step. If you wish that object files in libArduinoCore.a have vtables for the classes they define in the flash you need to use the plugin while compiling this library. Did you do that?

**Comment by theAndreas** [comment]
Ah ok. No I didn't, thought its only needed for linking. When I add it during compiling I get the following message:

Error		plugin support is disabled; configure with --enable-plugin

I think I have to configure and buld the compiler again. I did not know that either. So this will take some time ;-). I am not an expert in compiling the gcc! 

Also another question. In your description you mentioned: This plugin merely adds __flash attribute. As far as I know this attribute is only available for the c code. Compiled with gcc. So would it be also possible to add this feature for the g++ with the help of a plugin? This would eliminate the cumbersome PROGMEM handling.

**Comment by jcmvbkbc** [comment]
> When I add it during compiling I get the following message:
> Error plugin support is disabled; configure with --enable-plugin
> I think I have to configure and compile the compiler again.

Looks like that.

> So would it be also possible to add this feature for the g++ with the help of a plugin?

If you mean adding __flash keyword support to avr-g++ then it's significantly different from what this plugin does. AFAIU it would require adding support for address space qualifier recognition to the C++ front-end. I don't know this area good enough to say if it's feasible to do with a plugin.

**Comment by theAndreas** [comment]
>If you mean adding __flash keyword support to avr-g++ then it's significantly different from what this plugin does. AFAIU it would require adding support for address space qualifier recognition to the C++ front-end. I don't know this area good enough to say if it's feasible to do with a plugin.

Yeah, that's exactly what I meant. For the past few years, I've been hoping that this will be supported. But I don't think that's ever gonna happen. Today I had a closer look at the Clang compiler, which has also support for AVR since the last few versions. Maybe there is a better support for the Harvard architecture. But I could not find any information in the web. Seems to me the support for AVR is still experimental. Maybe its time to switch to ARM controller :D.

As soon as I finished building and gave it a try, I will let you know if it is working ;-). 

Thanks for your reply!

**Comment by theAndreas** [comment]
After a long night I was able to built the gcc with configure option --enable-plugin. I could successfully build the plugin for linux hosts, after installing libgmp3-dev. Because gmp.h was not found. I think this plugin will only work for the avr-gcc on linux. Using the plugin on windows with avr-g++ results in "cannot load plugin". Seems to me the plugin is hardware dependent. Sounds logical to me. I also built avr-g++ for windows with i686-w64-mingw32-gcc in version 9.2. I will provide it here. Maybe its useful for others:

Avr compilers with plugin enable:
Win64: https://ig5tf1xybtmow6m2.myfritz.net:49293/nas/filelink.lua?id=13321f5ff7f6c778
Linux: https://ig5tf1xybtmow6m2.myfritz.net:49293/nas/filelink.lua?id=878a3ff21b763122

To built the plugin for windows I used i686-w64-mingw32-g++ as host gcc in your make file and plugins from the windows avr-g++. Also the gmp.h file was missing. So I used the file from the libgmp3-dev package. Seems to me there is nothing really hardware dependent inside. I hope this is right. With all this settings I got the following linker errors:

```
i686-w64-mingw32-g++ -shared -I/home/andreas/omgwtfbbq/win64/bin/../lib/gcc/avr/9.2.0/plugin/include -Wl,--export-all-symbols /home/andreas/
omgwtfbbq/win64/bin/../lib/gcc/avr/9.2.0/plugin/cc1plus.exe.a avr-flash-vtbl.c -o avr-flash-vtbl.so -I./
/usr/bin/i686-w64-mingw32-ld: /tmp/cc28ZVde.o:avr-flash-vtbl.c:(.text+0x4): undefined reference to `cp_global_trees'
/usr/bin/i686-w64-mingw32-ld: /tmp/cc28ZVde.o:avr-flash-vtbl.c:(.text+0x10): undefined reference to `cp_global_trees'
/usr/bin/i686-w64-mingw32-ld: /tmp/cc28ZVde.o:avr-flash-vtbl.c:(.text+0x44): undefined reference to `register_callback'
collect2: error: ld returned 1 exit status
make: *** [Makefile:11: avr-flash-vtbl.so] Fehler 1
```

Your adapted make file for windows:
```
#HOST_GCC=g++-9
HOST_GCC=i686-w64-mingw32-g++
TARGET_GCC=/home/andreas/omgwtfbbq/win64/bin/avr-g++
PLUGIN_SOURCE_FILES = avr-flash-vtbl.c
GCCPLUGINS_DIR:= /home/andreas/omgwtfbbq/win64/bin/../lib/gcc/avr/9.2.0/plugin
CXXFLAGS+= -I$(GCCPLUGINS_DIR)/include -Wl,--export-all-symbols /home/andreas/omgwtfbbq/win64/bin/../lib/gcc/avr/9.2.0/plugin/cc1plus.exe.a



avr-flash-vtbl.so: $(PLUGIN_SOURCE_FILES)
	$(HOST_GCC) -shared $(CXXFLAGS) $^ -o $@ -I./
```

Do you have any ideas what goes wrong?

**Comment by jcmvbkbc** [comment]
> Using the plugin on windows with avr-g++ results in "cannot load plugin". Seems to me the plugin is hardware dependent.

It's OS-dependent, I don't think you can load linux ELF shared objects into windows processes with native windows mechanisms.

> With all this settings I got the following linker errors:
> /usr/bin/i686-w64-mingw32-ld: /tmp/cc28ZVde.o:avr-flash-vtbl.c:(.text+0x4): undefined reference to `cp_global_trees'
> /usr/bin/i686-w64-mingw32-ld: /tmp/cc28ZVde.o:avr-flash-vtbl.c:(.text+0x10): undefined reference to `cp_global_trees'
> /usr/bin/i686-w64-mingw32-ld: /tmp/cc28ZVde.o:avr-flash-vtbl.c:(.text+0x44): undefined reference to `register_callback'

Looks like the plugin needs to be linked with some sort of import library that exposes internals of cc1plus.exe. I tried the obvious and linked it with win64/lib/gcc/avr/9.2.0/plugin/cc1plus.exe.a but that didn't change anything.

**Comment by theAndreas** [comment]
There is already a post on stackoverflow facing the same issue. The answer sounds strange to me.
https://stackoverflow.com/questions/16957130/problems-with-building-the-gcc-plugin. But the plugin was built for linux I guess.

I also created a question https://stackoverflow.com/questions/60467609/building-gcc-plugin-for-windows-on-linux. Maybe someone knows what to do. I hope so!

> Looks like the plugin needs to be linked with some sort of import library that exposes internals of cc1plus.exe. I tried the obvious and linked it with win64/lib/gcc/avr/9.2.0/plugin/cc1plus.exe.a but that didn't change anything.

I have already tried the same. Seen here https://gcc.gnu.org/onlinedocs/gccint/Plugins-building.html.

**Comment by jcmvbkbc** [comment]
> The answer sounds strange to me.

Given that 'main' is missing the answer looks correct to me: instead of only compiling the plugin in the %.o rule the OP had it compiled and linked as executable there.

> But the plugin was built for linux I guess.

Yes.

> Maybe someone knows what to do.

Maybe it has something to do with C++ vs C name mangling? Dunno, haven't touched windows for ages.

**Comment by jcmvbkbc** [comment]
Oh, it seems that I see something interesting:

  $ file d000000.o 
  d000000.o: Intel amd64 COFF object file, no line number info, not stripped, 3 sections, symbol offset=0xbe, 5 symbols

  $ file avr-flash-vtbl.o 
  avr-flash-vtbl.o: Intel 80386 COFF object file, no line number info, not stripped, 5 sections, symbol offset=0x186, 18 symbols

See, they have different bitness.

**Comment by jcmvbkbc** [comment]
...and it builds for me with x86_64-w64-mingw32-g++

**Comment by theAndreas** [comment]
Oh really what have you done?  :D

**Comment by jcmvbkbc** [comment]
Changed the host compiler name and linked with cc1plus.exe.a

**Comment by theAndreas** [comment]
Oh I was using the wrong host compiler. Now I understand. The used version was for win32. Sorry my fault.

**Comment by jcmvbkbc** [comment]
BTW, the second dllexport directive in your SO question should go before the plugin_init function, not before the fn.

**Comment by theAndreas** [comment]
Seems to me there is still something wrong 

```
x86_64-w64-mingw32-g++ -shared -I/home/andreas/omgwtfbbq/win64/bin/../lib/gcc/avr/9.2.0/plugin/include -Wl,--export-all-symbols /home/andreas/omgwtfbbq/win64/bin/../lib/gcc/avr/9.
2.0/plugin/cc1plus.exe.a avr-flash-vtbl.c -o avr-flash-vtbl.so -I./
/usr/bin/x86_64-w64-mingw32-ld: /tmp/cckjipC0.o:avr-flash-vtbl.c:(.text+0x5f): undefined reference to `register_callback'
/usr/bin/x86_64-w64-mingw32-ld: /tmp/cckjipC0.o:avr-flash-vtbl.c:(.rdata$.refptr.cp_global_trees[.refptr.cp_global_trees]+0x0): undefined reference to `cp_global_trees'
collect2: error: ld returned 1 exit status

```

**Comment by jcmvbkbc** [comment]
/home/andreas/omgwtfbbq/win64/bin/../lib/gcc/avr/9.2.0/plugin/cc1plus.exe.a must go after avr-flash-vtbl.c That's how I do it locally:

```
avr-flash-vtbl.so: $(PLUGIN_SOURCE_FILES)
        $(HOST_GCC) -shared $(CXXFLAGS) $^ $(GCCPLUGINS_DIR)/cc1plus.exe.a -o $@
```

**Comment by theAndreas** [comment]
`BTW, the second dllexport directive in your SO question should go before the plugin_init function, not before the fn.`

Ok I will change it. I must also remove the static identifier from the fn function. If we use the dllexport directive we do not need the  -Wl,--export-all-symbols option. Its also working. But the output file did not change.

**Comment by theAndreas** [comment]
`/home/andreas/omgwtfbbq/win64/bin/../lib/gcc/avr/9.2.0/plugin/cc1plus.exe.a must go after avr-flash-vtbl.c That's how I do it locally:`

I didn't know that order mattered here. Its working now. This command was also not working
`gcc -print-file-name=plugin`, so I used the absolute pathes.

**Comment by theAndreas** [comment]
Really cool. Plugin is working in my environment and the vTables are in the .progmem section. Hardware is also running as expected! Thank you very much for your help.

**Comment by jcmvbkbc** [comment]
Cool, thanks for your feedback!
I've added clarifications to the README and mingw-specific stance to the Makefile to make it easier next time.

**Comment by theAndreas** [comment]
If you want you can add in your description that the Target Gcc has to be configured with option --enable-plugin. Otherwise the usage of plugins is not supported.

**Comment by theAndreas** [comment]
I will share the Compilers for Linux and Windows. The plugin is included in the archive. Mabe its helpful for others ;-). Avr-Gcc 9.2.0:

https://c.1und1.de/@520232801136547587/bdXynAy6S5ym-0B2PZPquA

Best regards Andreas
